bashcommands={"cd":"Cambia el directorio actual a otro directorio especificado",
"ls":"Lista los archivos y directorios en el directorio actual",
"mkdir":"Crea un nuevo directorio con el nombre especificado",
"rm":"Elimina archivos o directorios",
"cp":"Copia un archivo o directorio a otro lugar",
"mv":"Mueve un archivo o directorio a otro lugar",
"touch":"Crea un nuevo archivo con el nombre especificado",
"grep":"Busca una cadena de texto en un archivo o en la salida de otro comando",
"sed":"Edita el contenido de un archivo o la salida de otro comando",
"awk":"Procesa y manipula texto en archivos o en la salida de otros comandos",
"find":"Busca archivos o directorios en el sistema de archivos",
"chmod":"Cambia los permisos de acceso de un archivo o directorio",
"chown":"Cambia el propietario y el grupo de un archivo o directorio",
"echo":"Muestra un mensaje en la consola",
"printf":"Muestra un mensaje formateado en la consola",
"read":"Lee la entrada del usuario desde la consola"}